# Define the number of nodes
# If this number changed, remember to update setup-hosts.sh script
NUM_MASTER = 2
NUM_WORKER = 2

IP_NETWORK = "192.168.56."
IP_START_MASTER = 10
IP_START_WORKER = 20
IP_START_LB = 30


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Provision master nodes
  (1..NUM_MASTER).each do |i|
    config.vm.define "master-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-master-#{i}" # This name shown in the VirtualBox GUI
        vb.memory = (i == 1) ? 2048 : 1024
        vb.cpus = 2
      end
      node.vm.hostname = "master-#{i}"
      node.vm.network "private_network", ip: IP_NETWORK + "#{IP_START_MASTER + i}"
      node.vm.network "forwarded_port", guest: 22, host: 2210 + i
    end
  end

  # Provision worker nodes
  (1..NUM_WORKER).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-worker-#{i}" # This name shown in the VirtualBox GUI
        vb.memory = 1024
        vb.cpus = 1
      end
      node.vm.hostname = "worker-#{i}"
      node.vm.network "private_network", ip: IP_NETWORK + "#{IP_START_WORKER + i}"
      node.vm.network "forwarded_port", guest: 22, host: 2220 + i
    end
  end

  # Provision load balancer
  config.vm.define "loadbalancer" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-loadbalancer"
      vb.memory = 512
      vb.cpus = 1
    end
    node.vm.hostname = "loadbalancer"
    node.vm.network "private_network", ip: IP_NETWORK + "#{IP_START_LB}"
    node.vm.network "forwarded_port", guest: 22, host: 2230
  end

end
